@startuml yongli

:购买方: -> (定制芯片)
:购买方: -> (确认下单)
:购买方: -down-> (追踪订单信息)
:购买方: -up-> (确认结算信息)
(定制芯片) .> (确认下单) : <<include>>
(追踪订单信息) .> (同步订单信息): <<uses>>


 
:厂家: -left-> (接受订单)
:厂家: -down-> (同步订单信息)
:厂家: -left-> (确认结算信息)
(接受订单) .left.> (确认下单) : <<uses>>

@enduml